counter: counter.c
	gcc -Wall counter.c -o counter -lpthread

counter_mutex: counter_mutex.c mutex.c mutex.h
	gcc -Wall counter_mutex.c mutex.c -o counter_mutex -lpthread

counter_array: counter_array.c
	gcc -Wall counter_array.c -o counter_array -lpthread

counter_array_mutex: counter_array_mutex.c mutex.c mutex.h
	gcc -Wall counter_array_mutex.c mutex.c -o counter_array_mutex -lpthread

