queue_sem: queue_sem.c utils.c utils.h sem.c sem.h
	gcc -g -Wall queue_sem.c utils.c sem.c -o queue_sem -lpthread

queue_mysem: queue_sem.c utils.c utils.h mysem.c mysem.h
	gcc -g -Wall queue_mysem.c utils.c mysem.c -o queue_mysem -lpthread

