queue: queue.c utils.c utils.h
	gcc -g -Wall queue.c utils.c -o queue -lpthread

queue_mutex: queue_mutex.c utils.c utils.h
	gcc -g -Wall queue_mutex.c utils.c -o queue_mutex -lpthread

queue_cond: queue_cond.c utils.c utils.h
	gcc -g -Wall queue_cond.c utils.c -o queue_cond -lpthread

